name: quarto-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - matplotlib
  - wordcloud
  - scikit-learn
  - seaborn
  - numpy
  - scipy
  - statsmodels
  - jupyterlab
  - ipykernel
  - notebook

